name: Build Zig Vulkan GLFW

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} Zig Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.2

      - name: Install Vulkan + GLFW and build (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y \
            vulkan-tools \
            libvulkan-dev \
            vulkan-utility-libraries-dev \
            libglfw3 \
            libglfw3-dev
          make build TARGET="x86_64-linux"
          make build TARGET="aarch64-linux"

      - name: Install Vulkan SDK + GLFW and build (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install vulkan-sdk --no-progress
          choco install glfw --no-progress
          make build TARGET="x86_64-windows" EXT=".exe"
          make build TARGET="aarch64-windows" EXT=".exe"

      - name: Install Vulkan (MoltenVK) + GLFW and build (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install glfw molten-vk
          make build TARGET="x86_64-macos" EXT=""
          make build TARGET="aarch64-macos" EXT=""

